# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _component
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class Entity(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Entity, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Entity, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _component.new_Entity(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _component.delete_Entity
    __del__ = lambda self : None;
    def HasComponentType(*args): return _component.Entity_HasComponentType(*args)
    def HasComponentTypes(*args): return _component.Entity_HasComponentTypes(*args)
Entity_swigregister = _component.Entity_swigregister
Entity_swigregister(Entity)

class Component(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Component, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Component, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _component.new_Component(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _component.delete_Component
    __del__ = lambda self : None;
    __swig_setmethods__["entity"] = _component.Component_entity_set
    __swig_getmethods__["entity"] = _component.Component_entity_get
    if _newclass:entity = _swig_property(_component.Component_entity_get, _component.Component_entity_set)
Component_swigregister = _component.Component_swigregister
Component_swigregister(Component)



